namespace Organizations.Application.Features.Organizations.GetOrganizationInvitations;

public sealed record GetOrganizationInvitationsRequest(Guid Id) : QueryWithPaginationOptions, IRequest<GetOrganizationInvitationsResponse>;