namespace Organizations.Application.Features.Organizations.CreateOrganizationInvitation;

public sealed record CreateOrganizationInvitationRequest(Guid UserId, Guid OrganizationId) : IRequest<CreateOrganizationInvitationResponse>;